gurufinder/classroom/urls.py
from django.urls import path
from . import views

from module.views import course_modules, new_module
from page.views import new_page_module, page_detail, mark_page_as_done
from quiz.views import new_quiz, new_question, quiz_detail, take_quiz, submit_attempt, attempt_detail
from assignment.views import new_assignment, assignment_detail, new_submission
from question.views import new_student_question, questions, question_detail, mark_as_answer, vote_answer




app_name = 'classroom'
urlpatterns = [
    path('', views.ClassroomListView.as_view(), name='classroom_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/<int:subject_id>/', views.course_detail, name='course'),
    path('<slug:slug>/<int:subject_id>/modules/', course_modules, name='modules'),
    path('<slug:slug>/<int:subject_id>/modules/new-module/', new_module, name='new-module'),
    #pages
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/new-page/', new_page_module, name='new-page'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/', page_detail, name='page-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/done/', mark_page_as_done, name='mark-page-as-done'),

    #Quizzes
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/new-quiz', new_quiz, name='new-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/new-question', new_question, name='new-question'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/', quiz_detail, name='quiz-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take', take_quiz, name='take-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take/submit', submit_attempt, name='submit-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/<int:attempt_id>/results', attempt_detail, name='attempt-detail'),

    #Assignment
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/new-assignment', new_assignment, name='new-assignment'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>', assignment_detail, name='assignment-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>/start', new_submission, name='start-assignment'),

    #Submissions
	path('<slug:slug>/<int:subject_id>/submissions', views.submissions, name='submissions'),
	path('<slug:slug>/<int:subject_id>/student-submissions', views.student_submissions, name='student-submissions'),
	path('<slug:slug>/<int:subject_id>/submissions/<int:grade_id>/grade', views.grade_submission, name='grade-submission'),

    #Questions
    path('<slug:slug>/<int:subject_id>/questions', questions, name='questions'),
    path('<slug:slug>/<int:subject_id>/questions/new-question', new_student_question, name='new-student-question'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>', question_detail, name='question-detail'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/vote', vote_answer, name='vote-answer'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/<int:answer_id>/mark-as-answer', mark_as_answer, name='mark-as-answer'),

    #extra content
    path('<slug:slug>/<int:subject_id>/extra-content', views.LessonListView.as_view(), name='lesson_list'),
    path('<slug:slug>/<int:subject_id>/extra-content/create', views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    # path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/<int:lesson_id>/', views.lesson_completed, name='lesson_complete'),
    # path('<str:classroom>/<str:subject>/<slug:slug>/<int:id>/', views.lesson_not_completed, name='lesson_not_completed'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),
    path('<str:classroom>/<int:subject_id>/extra-content/<int:lesson_id>/mark-as-done/', views.mark_lesson_as_done,name='mark-lesson-as-done'),

]

gurufinder/direct/urls.py
from django.urls import path, include
from . import views

app_name = 'direct'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('message/<username>', views.directs, name='message'),
    path('send/', views.send_direct, name='send_direct'),
    path('new/', views.user_search, name='usersearch'),
    path('new/<username>', views.new_conversation, name='newconversation'),
]

gurufinder/gurufinder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls
from accounts import views as accounts_views
from accounts.views import TutorListView, TutorDetailView, BookingView, SearchTutorLanguage #ApplicationView,

urlpatterns = [
    path('', accounts_views.index, name='index'),
    path('about/', accounts_views.about, name='about'),
    path('how-it-works/', accounts_views.how_it_works, name='how_it_works'),
    path('start-tutoring/', accounts_views.tutor_application, name='application'),
    path('search-for-tutors/', TutorListView.as_view(), name='tutor_list'),
    path('search-for-tutors/search-language/', SearchTutorLanguage.as_view(), name='search_language'),
    path('search-for-tutors/<int:pk>/', TutorDetailView.as_view(), name='tutor_detail'),
    path('search-for-tutors/<int:pk>/book/', BookingView.as_view(), name='booking'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('classroom.urls')),
    path('accounts/', include('accounts.urls')),
    path('messages/', include('direct.urls')),
    path('admin/', admin.site.urls),
    path('email/', include(email_urls)),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gurufinder/question/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

#3rd apps field
from ckeditor.fields import RichTextField

# Create your models here.

VOTES_CHOICES = (
	('U', 'Up Vote'),
	('D', 'Down Vote'),
)

class Question(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='question_user')
	title = models.CharField(max_length=300)
	body = RichTextField()
	created_date = models.DateTimeField(auto_now_add=True)
	update_date = models.DateTimeField(auto_now_add=True)
	has_accepted_answer = models.BooleanField(default=False)

	def __str__(self):
		return self.title

	def get_answers_count(self):
		return Answer.objects.filter(question=self).count()


class Answer(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answer_user')
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	body = RichTextField()
	created_date = models.DateTimeField(auto_now_add=True)
	update_date = models.DateTimeField(auto_now_add=True)
	votes = models.IntegerField(default=0)
	is_accepted_answer = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

	def calculate_votes(self):
		u_votes = Votes.objects.filter(answer=self, vote='U').count()
		d_votes = Votes.objects.filter(answer=self, vote='D').count()
		self.votes = u_votes - d_votes
		self.save()
		return self.votes

class Votes(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='votes_user')
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='answer_votes')
	vote = models.CharField(choices=VOTES_CHOICES, max_length=1)
	date = models.DateTimeField(auto_now_add=True)

gurufinder/question/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from question.models import Question, Answer

class QuestionForm(forms.ModelForm):
	title = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)
	body = forms.CharField(widget=CKEditorWidget())

	class Meta:
		model = Question
		fields = ('title', 'body')

class AnswerForm(forms.ModelForm):
	body = forms.CharField(widget=CKEditorWidget())

	class Meta:
		model = Answer
		fields = ('body',)

gurufinder/question/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, HttpResponse
from django.core.paginator import Paginator

from question.models import Question, Answer, Votes
from question.forms import QuestionForm, AnswerForm

from classroom.models import Subject


def new_student_question(request, **kwargs):
    user = request.user
    subject_id = kwargs.get('subject_id')
    #subjects = Subject.objects.get(id=subject_id)
    subjects = Subject.objects.all()

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            body = form.cleaned_data.get('body')
            q = Question.objects.create(user=user, title=title, body=body)
            #subject.questions.add(q)
            for subject in subjects:
                subject.questions.add(q)
            return redirect('classroom:questions', slug=subject.slug, subject_id=subject.id)
    else:
        form = QuestionForm()
    context = {
        'form': form,
    }
    return render(request, 'question/newquestion.html', context)


def questions(request, **kwargs):
    subject_id = kwargs.get('subject_id')
    subject = Subject.objects.get(id=subject_id)
    questions = subject.questions.all()

    # Pagination
    paginator = Paginator(questions, 10)
    page_number = request.GET.get('page')
    questions_data = paginator.get_page(page_number)

    context = {
        'subject': subject,
        'questions': questions_data,
    }
    return render(request, 'question/questions.html', context)


def question_detail(request, **kwargs):
    user = request.user
    # moderator = False
    question_id = kwargs.get('question_id')
    subject_id = kwargs.get('subject_id')
    subject = Subject.objects.get(id=subject_id)
    question = Question.objects.get(id=question_id)

    correct_answer = Answer.objects.filter(question=question, is_accepted_answer=True)
    rest_answers = Answer.objects.filter(question=question)

    answers = correct_answer | rest_answers

    # if user == subject.classroom.bookings.tutor_id.user or user == question.user:
    #     moderator = True

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            body = form.cleaned_data.get('body')
            Answer.objects.create(user=user, question=question, body=body)
            return redirect('classroom:question-detail', slug=subject.slug, subject_id=subject_id, question_id=question_id)
    else:
        form = AnswerForm()
    context = {
        'question': question,
        'answers': answers,
        'subject': subject,
        'form': form,
        # 'moderator': moderator,
    }
    return render(request, 'question/question.html', context)


def mark_as_answer(request, **kwargs):
    user = request.user
    answer_id = kwargs.get('answer_id')
    question_id = kwargs.get('question_id')
    subject_id = kwargs.get('subject_id')
    subject = Subject.objects.get(id=subject_id)
    question = Question.objects.get(id=question_id)

    if user == subject.classroom.bookings.tutor_id.user or user == question.user:
        answer = Answer.objects.get(id=answer_id)
        answer.is_accepted_answer = True
        answer.save()
        question.has_accepted_answer = True
        question.save()
        return redirect('classroom:question-detail', slug=subject.slug, subject_id=subject_id, question_id=question_id)
    else:
        return HttpResponseForbidden()


def vote_answer(request, **kwargs):
    user = request.user
    subject_id = kwargs.get('subject_id')
    question_id = kwargs.get('question_id')
    answer_id = request.POST['answer_id']
    vote_type = request.POST['vote_type']
    try:
        answer = Answer.objects.get(id=answer_id)
        voted = Votes.objects.filter(user=user, answer=answer)
        if voted:
            voted.delete()
        else:
            if vote_type == 'U':
                Votes.objects.create(user=user, answer=answer, vote='U')
            else:
                Votes.objects.create(user=user, answer=answer, vote='D')
        return HttpResponse(answer.calculate_votes())
    except Exception as e:
        raise e

gurufinder/question/templates/question/newquestion.html
{% extends 'base.html' %}
{% load static %}

        
{% block content %}

<div class="container pb-5 pt-4">
  <div class="row center-align">
    <div class="col-md-12">


      <form method="post" enctype="multipart/form-data" action="" role="form">
        {% csrf_token %}
      <h3 class="display-6" style="color:#ff5722;">Question</h3>


            <div class="input-field col-md-12">
              {{ form.title }}
              <label for="title">Title</label>
            </div>

            <div class="input-field col-md-12">
              {{ form.body }}
            </div>


        <div class="row">
          <div class="col-md-12">
            <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
          </div>
        </div>


        <div class="field">
        <p class="control">
          <button type="submit" value="login" class="btn waves-effect waves-light">
            Create new question
          </button>
        </p>
      </div>

      </form>

  </div>
  </div>
</div>
{% endblock %}

gurufinder/question/templates/question/question.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container pb-5">
<div class="section">
	<h4 class="display-6" style="color:#ff5722;">{{ subject.name }}</h4>
	<div class="divider"></div>
</div>

<div class="row g-0">

<div class="col-md-3">
      <ul class="collection with-header">
                <li class="collection-header"><h4 class="display-6">Classroom</h4></li>
                <a href="{% url 'classroom:course' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Home</a>
                <a href="{% url 'classroom:modules' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Module</a>
                <a href="{% url 'classroom:submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Submissions</a>
                <a href="{% url 'classroom:questions' slug=subject.slug  subject_id=subject.id %}" class="collection-item active">Questions</a>
              <a href="{% url 'classroom:lesson_list'  slug=subject.slug subject_id=subject.id %}" class="collection-item">Extra Content</a>

                  {% if user.is_tutor %}
                <li class="collection-header"><h4 class="display-6">Teacher</h4></li>
                <a href="{% url 'classroom:student-submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Student Submissions</a>
                    {% endif %}

              </ul>
</div>

<div class="col-md-9 gx-5">


  <div class="section">
    <h7 class="display-6">{{ question.title|capfirst }}</h7>
    <div class="divider mb-3 mt-4"></div>

    <div>
      {{ question.body | safe }}
    </div>

    <div>
      <div class="divider"></div>
      <h4><b>Asked by</b></h4>
    </div>

    <div class="col-md-12">
      <div class="card-panel grey lighten-5 z-depth-1">

      <div class="row">
      <div class="col-md-2">
      {% if question.user.image %}
        <img src="{{ question.user.image.url }}" class="circle responsive-img">
      {% else %}
        <img src="#" class="circle responsive-img">
      {% endif %}
      </div>

      <div class="col-md-10">
        <p class="black-text"><b>{{ question.user.get_full_name|title }}</b> @{{ question.user.email }}</p>
        <p class="black-text"><b>Asked: </b>{{question.created_date | naturaltime }}</p>
      </div>
      </div>

      </div>
    </div>

    <div class="col-md-12">
      <h5><b>Answers: {{ answers.count }}</b></h5>
      <div class="divider mt-4"></div>
    </div>
    {% csrf_token %}
    <input type="hidden" name="url_path" value="{{ request.get_full_path }}">



    <div class="col-md-12">

      {% for answer in answers %}
      <div class="col-md-12">
      <div class="card-panel grey lighten-5 z-depth-2">

      {% if answer.is_accepted_answer == True %}
      <div class="col-md-12 right-align">
        <i class="material-icons medium green-text">done</i>
      </div>
      {% endif %}

      <div class="col-md-12">
        {{ answer.body | safe }}
      </div>

      <div class="row pt-5">
      <div class="col-md-2">
      {% if answer.user.image %}
        <img src="{{ answer.user.image.url }}" class="circle responsive-img">
      {% else %}
        <img src="#" class="circle responsive-img">
      {% endif %}
      </div>

      <div class="col-md-10">
        <p class="black-text"><b>{{ answer.user.get_full_name|title }}</b> @{{ answer.user.email }}</p>
        <p class="black-text"><b>Answered: </b>{{answer.created_date | naturaltime }}</p>
      </div>

      <div class="col-md-12 pt-5">
        <a href="" class="vote" vote-type="U" answer-id="{{ answer.id }}"><i class="material-icons">thumb_up</i>Up vote</a>
        <a href="" class="vote" vote-type="D" answer-id="{{ answer.id }}"><i class="material-icons">thumb_down</i>Down vote</a> 

        {% if user == question.user %}
          <a href="{% url 'classroom:mark-as-answer' slug=subject.slug subject_id=subject.id question_id=question.id answer_id=answer.id %}"><i class="material-icons">done</i>Mark as answer</a>
        {% endif %}

        <span class="card-title"><b>  Votes</b></span>
        <span id="answerVotes{{ answer.id }}" class="card-title"><b>{{ answer.votes }}</b></span>

      </div>

      </div>

      </div>
    </div>
    {% endfor %}   

    </div>


    <div class="col-md-12">
      <h5><b>Your answer</b></h5>
      <div class="divider"></div>

      <div class="pt-2">
        <form method="post" action="" role="form" class="col-md-12">
          {% csrf_token %}
          <div class="input-field col-md-12">
            {{ form.body }}
          </div>
          <div class="input-field col-md-12">
            <button type="submit" value="login" class="btn waves-effect waves-light">
              Submit
            </button>
          </div>
          
        </form>
          
        
      </div>

    </div>





    <div class="col-md-12 m12 center-align">
      {% if questions.has_previous %}
        <a href="?page={{ questions.previous_page_number }}" class="btn"><i class="material-icons">arrow_back</i>Back</a>
      {% endif %}

      {% if questions.has_next %}
        <a href="?page={{ questions.next_page_number }}" class="btn"><i class="material-icons">add</i>Load more</a>
      {% endif %}  

    </div>
  


  </div>
  
</div>


</div>
</div>

{% endblock %}

gurufinder/question/templates/question/questions.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container pb-5">
<div class="section">
	<h4 class="display-6" style="color:#ff5722;">{{ subject.name }}</h4>
	<div class="divider"></div>
</div>

<div class="row g-0">

<div class="col-md-3">
      <ul class="collection with-header">
                <li class="collection-header"><h4 class="display-6">Classroom</h4></li>
                <a href="{% url 'classroom:course' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Home</a>
                <a href="{% url 'classroom:modules' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Module</a>
                <a href="{% url 'classroom:submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Submissions</a>
                <a href="{% url 'classroom:questions' slug=subject.slug  subject_id=subject.id %}" class="collection-item active">Questions</a>
              <a href="{% url 'classroom:lesson_list'  slug=subject.slug subject_id=subject.id %}" class="collection-item">Extra Content</a>

                  {% if user.is_tutor %}
                <li class="collection-header"><h4 class="display-6">Teacher</h4></li>
                <a href="{% url 'classroom:student-submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Student Submissions</a>
                    {% endif %}

              </ul>
</div>

<div class="col-md-9 gx-5">

  <a href="{% url 'classroom:new-student-question' slug=subject.slug subject_id=subject.id %}" class="btn-floating btn-large waves-effect waves-light red right"><i class="material-icons">add</i></a>

  <div class="section">
    <h4 class="display-6">Questions</h4>
    <div class="divider"></div>


    {% for question in questions %}
   <div class="border card box-shadow-hover mb-3">
          <div class="row g-0">
              <div class="col-md-2">
                  <img src="{{ question.user.image.url }}" class="article-img" alt="{{ question.user.first_name }}">
              </div>
              <div class="col-md-7">
                  <div class="card-body vl">
                      <h7><a class="text-dark">{{ question.user.get_full_name|title }}@{{ question.user.email }}</a></small>
                      <h6 class="text-primary"><a href="{% url 'classroom:question-detail' slug=subject.slug subject_id=subject.id question_id=question.id %}" style="text-decoration: none">{{ question.title|capfirst }}</a></h6>
                      {% if question.title|add:question.body|length > 150 %}
                        <h7 class="text-muted">{{ question.body|truncatechars:110 }}<a href="{% url 'classroom:question-detail' slug=subject.slug subject_id=subject.id question_id=question.id %}" style="text-decoration: none;">read more</a></h7>
                      {% else %}
                        <h6 class="text-muted"><a href="{% url 'classroom:question-detail' slug=subject.slug subject_id=subject.id question_id=question.id %}" style="text-decoration: none;">{{ question.bio|capfirst }}</a></h6>
                      {% endif %}
                  </div>
              </div>
              <div class="secondary-content col-md-3 text-center pt-3">
                  <h5>{{ question.get_answers_count }} Answers</h5>
                  <h5>
                      {% if question.has_accepted_answer == True %}
                        <span class="new badge green" data-badge-caption="Answered"></span>
                      {% else %}
                        <span class="new badge orange" data-badge-caption="Unanswered"></span>
                      {% endif %}

                  </h5>
              </div>
          </div>
      </div>
    {% endfor %}


    <div class="col-md-12 m12 center-align">
      {% if questions.has_previous %}
        <a href="?page={{ questions.previous_page_number }}" class="btn"><i class="material-icons">arrow_back</i>Back</a>
      {% endif %}

      {% if questions.has_next %}
        <a href="?page={{ questions.next_page_number }}" class="btn"><i class="material-icons">add</i>Load more</a>
      {% endif %}  

    </div>
  


  </div>
  
</div>


</div>
</div>

{% endblock %}