gurufinder/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import SignUpView, StudentSignUpView, TutorSignUpView, ProfileView, ProfileUpdateView, TutorBookedSession, ActiveSession
from . import views as acccount_views

app_name = 'accounts'
urlpatterns = [
    path('signup/', include([
        path('', SignUpView.as_view(), name='signup'),
        path('student/', StudentSignUpView.as_view(), name='student_signup'),
        path('tutor/', TutorSignUpView.as_view(), name='tutor_signup'),
    ])),
    path('student-wallet/', acccount_views.student_wallet, name='student_wallet'),
    path('tutor-wallet/', acccount_views.tutor_wallet, name='tutor_wallet'),
    # path('student-wallet/add-amount/', acccount_views.student_add_amount, name='student_add_amount'),
    path('booked-sessions/', ActiveSession.as_view(), name='booked_sessions'),
    path('booked-sessions/end-session/<int:id>/', acccount_views.end_session, name='end_session'),
    path('end-session-rating-student/<int:id>/', acccount_views.end_session_rating_student, name='end_session_rating_student'),
    path('end-session-rating-tutor/<int:id>/', acccount_views.end_session_rating_tutor,name='end_session_rating_tutor'),
    path('booked-requests/', TutorBookedSession.as_view(), name='tutor_bookings'),
    path('booked-requests/deny/<int:id>/', acccount_views.deny_request, name='deny_request'),
    path('booked-requests/accept/<int:id>/', acccount_views.accept_request, name='accept_request'),
    path('availability/', acccount_views.availability, name='availability'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<username>/', ProfileUpdateView.as_view(), name='profile_update'),
]

gurufinder/classroom/urls.py
from django.urls import path
from . import views

from module.views import course_modules, new_module
from page.views import new_page_module, page_detail, mark_page_as_done
from quiz.views import new_quiz, new_question, quiz_detail, take_quiz, submit_attempt, attempt_detail
from assignment.views import new_assignment, assignment_detail, new_submission
from question.views import new_student_question, questions, question_detail, mark_as_answer, vote_answer




app_name = 'classroom'
urlpatterns = [
    path('', views.ClassroomListView.as_view(), name='classroom_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/<int:subject_id>/', views.course_detail, name='course'),
    path('<slug:slug>/<int:subject_id>/modules/', course_modules, name='modules'),
    path('<slug:slug>/<int:subject_id>/modules/new-module/', new_module, name='new-module'),
    #pages
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/new-page/', new_page_module, name='new-page'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/', page_detail, name='page-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/done/', mark_page_as_done, name='mark-page-as-done'),

    #Quizzes
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/new-quiz', new_quiz, name='new-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/new-question', new_question, name='new-question'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/', quiz_detail, name='quiz-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take', take_quiz, name='take-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take/submit', submit_attempt, name='submit-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/<int:attempt_id>/results', attempt_detail, name='attempt-detail'),

    #Assignment
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/new-assignment', new_assignment, name='new-assignment'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>', assignment_detail, name='assignment-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>/start', new_submission, name='start-assignment'),

    #Submissions
	path('<slug:slug>/<int:subject_id>/submissions', views.submissions, name='submissions'),
	path('<slug:slug>/<int:subject_id>/student-submissions', views.student_submissions, name='student-submissions'),
	path('<slug:slug>/<int:subject_id>/submissions/<int:grade_id>/grade', views.grade_submission, name='grade-submission'),

    #Questions
    path('<slug:slug>/<int:subject_id>/questions', questions, name='questions'),
    path('<slug:slug>/<int:subject_id>/questions/new-question', new_student_question, name='new-student-question'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>', question_detail, name='question-detail'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/vote', vote_answer, name='vote-answer'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/<int:answer_id>/mark-as-answer', mark_as_answer, name='mark-as-answer'),

    #extra content
    path('<slug:slug>/<int:subject_id>/extra-content', views.LessonListView.as_view(), name='lesson_list'),
    path('<slug:slug>/<int:subject_id>/extra-content/create', views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    # path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/<int:lesson_id>/', views.lesson_completed, name='lesson_complete'),
    # path('<str:classroom>/<str:subject>/<slug:slug>/<int:id>/', views.lesson_not_completed, name='lesson_not_completed'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),
    path('<str:classroom>/<int:subject_id>/extra-content/<int:lesson_id>/mark-as-done/', views.mark_lesson_as_done,name='mark-lesson-as-done'),

]

gurufinder/direct/urls.py
from django.urls import path, include
from . import views

app_name = 'direct'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('message/<username>', views.directs, name='message'),
    path('send/', views.send_direct, name='send_direct'),
    path('new/', views.user_search, name='usersearch'),
    path('new/<username>', views.new_conversation, name='newconversation'),
]

gurufinder/gurufinder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls
from accounts import views as accounts_views
from accounts.views import TutorListView, TutorDetailView, BookingView, SearchTutorLanguage #ApplicationView,

urlpatterns = [
    path('', accounts_views.index, name='index'),
    path('about/', accounts_views.about, name='about'),
    path('how-it-works/', accounts_views.how_it_works, name='how_it_works'),
    path('start-tutoring/', accounts_views.tutor_application, name='application'),
    path('search-for-tutors/', TutorListView.as_view(), name='tutor_list'),
    path('search-for-tutors/search-language/', SearchTutorLanguage.as_view(), name='search_language'),
    path('search-for-tutors/<int:pk>/', TutorDetailView.as_view(), name='tutor_detail'),
    path('search-for-tutors/<int:pk>/book/', BookingView.as_view(), name='booking'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('classroom.urls')),
    path('accounts/', include('accounts.urls')),
    path('messages/', include('direct.urls')),
    path('admin/', admin.site.urls),
    path('email/', include(email_urls)),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gurufinder/classroom/forms.py
from django import forms
from .models import Comment, Reply, Lesson


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['lesson_id', 'name', 'position', 'video', 'ppt', 'Notes']


# class LessonCompleted(forms.ModelForm):
#     class Meta:
#         model = Lesson
#         fields = ['completed']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

        labels = {'body': 'comment'}

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'cols': 70, 'placeholder': "Enter Your Comment"}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply_body']

        widgets = {
            'reply_body': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'cols': 10})
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

gurufinder/classroom/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, FormView
from .models import Classroom, Subject, Lesson, TimeSlots, Grade
from django.urls import reverse_lazy
from .forms import CommentForm, ReplyForm, LessonForm
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from completion.models import Completion


class ClassroomListView(ListView):
    context_object_name = 'classrooms'
    model = Classroom
    template_name = 'classroom/classroom_list_view.html'


# class SubjectListView(DetailView):
#     context_object_name = 'classrooms'
#     extra_context = {
#         'slots': TimeSlots.objects.all()
#     }
#     model = Classroom
#     template_name = 'classroom/subject_list_view.html'


class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'classroom/lesson_list_view.html'

    def get_context_data(self, *args, **kwargs):
        context = super(LessonListView, self).get_context_data(*args, **kwargs)
        user = self.object.classroom.bookings.student_id.user
        subject = self.object.id
        context['lesson_completions'] = Completion.objects.filter(user=user, subject=subject).values_list('lesson__pk', flat=True)

        return context


class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'classroom/lesson_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        subject = self.object.subject
        lesson = self.object.id
        context['completed'] = Completion.objects.filter(subject=subject.id, user=self.request.user, lesson=lesson).exists()

        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(request=self.request)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form_name == 'form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name == 'form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)

    def get_success_url(self):
        self.object = self.get_object()
        classroom = self.object.Classroom
        subject = self.object.subject
        return reverse_lazy('classroom:lesson_detail', kwargs={'classroom': classroom.slug, 'subject': subject.slug, 'slug': self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

def mark_lesson_as_done(request, **kwargs):
	user = request.user
	subject_id = kwargs.get('subject_id')
	lesson_id = kwargs.get('lesson_id')
	lesson = Lesson.objects.get(id=lesson_id)
	subject = Subject.objects.get(id=subject_id)
	Completion.objects.create(user=user, subject=subject, lesson=lesson)

	return redirect('classroom:lesson_list', slug=subject.slug, subject_id=subject_id)


class LessonCreateView(CreateView):
    form_class = LessonForm
    context_object_name = 'subject'
    model = Subject
    template_name = 'classroom/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        classroom = self.object.classroom
        return reverse_lazy('classroom:lesson_list', kwargs={'slug': self.object.slug, 'subject_id': self.object.id})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Classroom = self.object.classroom
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LessonUpdateView(UpdateView):
    fields = ['name', 'position', 'video', 'ppt', 'Notes']
    model = Lesson
    template_name = 'classroom/lesson_update.html'
    context_object_name = 'lessons'


class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'classroom/lesson_delete.html'

    def get_success_url(self):
        print(self.object)
        classroom = self.object.Classroom
        subject = self.object.subject
        return reverse_lazy('classroom:lesson_list', kwargs={'classroom': classroom.slug, 'slug': subject.slug})


def lesson_completed(request, **kwargs):
    lesson = Lesson.objects.get(id=kwargs.get('lesson_id'))

    if 'completed' in request.POST:
        lesson.completed = True
        lesson.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    elif 'not_completed' in request.POST:
        lesson.completed = False
        lesson.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, 'classroom/lesson_detail_view.html')


# def lesson_not_completed(request, **kwargs):
#     lesson = Lesson.objects.get(id=kwargs.get('id'))
#     print('executed not completed')
#     print(request.POST)
#     print(request.POST)
#     if 'submit' in request.POST:
#         if 'not_completed' == request.POST.get('submit'):
#             lesson.completed = False
#             lesson.save()
#
#         return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
#
#     return render(request, 'classroom/lesson_detail_view.html')

class SubjectListView(DetailView):
    context_object_name = 'classrooms'
    extra_context = {
        'slots': TimeSlots.objects.all()
    }
    model = Classroom
    template_name = 'classroom/subject_list_view.html'


@login_required
def course_detail(request, **kwargs):
	user = request.user
	subject = Subject.objects.get(id=kwargs.get('subject_id'))

	context = {
		'subject': subject,
	}

	return render(request, 'classroom/course.html', context)


def submissions(request, **kwargs):
    user = request.user
    subject_id = kwargs.get('subject_id')
    subject = Subject.objects.get(id=subject_id)
    grades = Grade.objects.filter(subject=subject, submission__user=user)
    context = {
		'grades': grades,
		'subject': subject
	}
    return render(request, 'classroom/submissions.html', context)


def student_submissions(request, **kwargs):
    user = request.user
    subject_id = kwargs.get('subject_id')
    subject = Subject.objects.get(id=subject_id)
    if user != subject.classroom.bookings.tutor_id.user:
	    return HttpResponseForbidden()
    else:
        grades = Grade.objects.filter(subject=subject)
        context = {
			'subject': subject,
			'grades': grades,
        }
    return render(request,'classroom/studentgrades.html', context)


def grade_submission(request, **kwargs):
    user = request.user
    grade_id = kwargs.get('grade_id')
    subject_id = kwargs.get('subject_id')
    subject = Subject.objects.get(id=subject_id)
    grade = Grade.objects.get(id=grade_id)

    if user != subject.classroom.bookings.tutor_id.user:
	    return HttpResponseForbidden()
    else:
	    if request.method == 'POST':
		    points = request.POST.get('points')
		    grade.points = points
		    grade.status = 'graded'
		    grade.graded_by = user
		    grade.save()
		    return redirect('classroom:student-submissions', slug=subject.slug, subject_id=subject.id)
    context = {
		'subject': subject,
		'grade': grade,
	}

    return render(request, 'classroom/gradesubmission.html', context)

gurufinder/classroom/templates/classroom/course.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="section">
        <h4 class="display-6" style="color:#ff5722;">{{ subject.name }}</h4>
        <div class="divider"></div>
    </div>

    <div class="row g-0">

      <div class="col-lg-3">
            <ul class="collection with-header">
              <li class="collection-header"><h4 class="display-6" >Classroom</h4></li>
              <a href="{% url 'classroom:course' slug=subject.slug  subject_id=subject.id %}" class="collection-item active">Home</a>
              <a href="{% url 'classroom:modules' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Module</a>
              <a href="{% url 'classroom:submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Submissions</a>
              <a href="{% url 'classroom:questions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Questions</a>
              <a href="{% url 'classroom:lesson_list'  slug=subject.slug subject_id=subject.id %}" class="collection-item">Extra Content</a>


              {% if user.is_tutor %}
                <li class="collection-header"><h4 class="display-6" >Teacher</h4></li>
                <a href="{% url 'classroom:student-submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Student Submissions</a>
              {% endif %}

            </ul>
      </div>

        <div class="col-lg-9 gx-5">

          {% if user.is_tutor %}
            <a class="btn-floating btn-large waves-effect waves-light red right"><i class="material-icons">add</i></a>
          {% endif %}

          <div class="section">
            <h4 class="display-6">Recent announcements</h4>
            <div class="divider"></div>
          </div>

            <div>

            </div>

            {{ subject.description | safe }}

        </div>

    </div>
    <div>


    </div>
  </div>
<div class="pb-5"></div>
<div class="pb-5"></div>


{% endblock %}

gurufinder/classroom/templates/classroom/gradesubmission.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container pb-5 pt-4">
<div class="section">
	<h4 class="display-6" style="color:#ff5722;">{{ subject.name }}</h4>
	<div class="divider"></div>
</div>

<div class="row">

<div class="col-md-3">
      <ul class="collection with-header">
        <li class="collection-header"><h4>Classroom</h4></li>
                <a href="{% url 'classroom:course' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Home</a>
                <a href="{% url 'classroom:modules' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Module</a>
                <a href="{% url 'classroom:submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Submissions</a>
                <a href="{% url 'classroom:questions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Questions</a>

        {% if user.is_tutor %}
          <li class="collection-header"><h4>Teacher</h4></li>
          <a href="{% url 'classroom:student-submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item active">Student Submissions</a>
        {% endif %}

      </ul>
</div>

<div class="col-md-9">

  <div class="section">
    <h4><b>{{ grade.submission.user.get_full_name|title }}</b></h4>
    <h5>@{{ grade.submission.user.email }}</h5>

    <div class="col-md-12 center-align pt-4 pb-3">
      <div class="card-panel">
        <h4 class="card-title">{{ grade.submission.comment }}</h4>
        <a href="{{ grade.submission.file.url }}" download>
        <i class="material-icons">download</i>{{ grade.submission.get_file_name }} - Download</a>      
      </div>
    </div>

  <div class="col-md-12">
  <form method="post" action="{% url 'classroom:grade-submission' slug=subject.slug  subject_id=subject.id grade_id=grade.id %}" role="form" class="col-md-12">
    {% csrf_token %}
    <h4>Assignment maximum points: <b>{{ grade.submission.assignment.points }}</b></h4>

    <div class="input-field col-md-12">
      <i class="material-icons prefix">plus_one</i>
      <input id="icon_prefix" type="text" name="points" class="validate">
      <label for="icon_prefix">Points</label>
    </div>

    <div class="col-md-12">
        <button type="submit" value="login" class="btn waves-effect waves-light">
          Submit
        </button>
    </div>
  </form>
</div>




  </div>
  
</div>


</div>
</div>

{% endblock %}

gurufinder/classroom/templates/classroom/lesson_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container pb-5">
    <section id="best-features" class="text-center">
      <h2 class="my-5 font-weight-bold" style="color:#ff5722;" >Create a Lesson</h2>
      <!-- class row for description-->
      <div class="row d-flex justify-content-center mb-4">
        <!-- class column -->
        <div class="col-md-8">
          <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate hic provident nulla repellat facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis est sit pariatur.</p>
        </div>
      </div>
    </section>


    <form method="post" enctype="multipart/form-data">
      <div class="form-group">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-success btn-lg btn-block mt-2" type="submit" value="Create">
      </div>
    </form>
  </div>

{% endblock %}

gurufinder/classroom/templates/classroom/lesson_list_view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container pb-5">
    <div class="section">
        <h4 class="display-6" style="color:#ff5722;">{{ subjects.name }}</h4>
        <div class="divider"></div>
    </div>

    <div class="row g-0">

        <div class="col-lg-3">
              <ul class="collection with-header">
                <li class="collection-header"><h4 class="display-6">Classroom</h4></li>
                <a href="{% url 'classroom:course' slug=subjects.slug  subject_id=subjects.id %}" class="collection-item">Home</a>
                <a href="{% url 'classroom:modules' slug=subjects.slug  subject_id=subjects.id %}" class="collection-item">Module</a>
                <a href="{% url 'classroom:submissions' slug=subjects.slug  subject_id=subjects.id %}" class="collection-item">Submissions</a>
                <a href="{% url 'classroom:questions' slug=subjects.slug  subject_id=subjects.id %}" class="collection-item">Questions</a>
                  <a href="{% url 'classroom:lesson_list' slug=subjects.slug subject_id=subjects.id %}" class="collection-item active">Extra Content</a>

                  {% if user.is_tutor %}
                <li class="collection-header"><h4 class="display-6">Teacher</h4></li>
                <a href="{% url 'classroom:student-submissions' slug=subjects.slug  subject_id=subjects.id %}" class="collection-item">Student Submissions</a>
                    {% endif %}

              </ul>
        </div>

    <div class="col-lg-9 gx-5">
      <div class="section">
        <h4 class="display-6">Extra Contents</h4>
        <div class="divider"></div>

        <ul class="collapsible">
          <li>
            <div class="collapsible-header"><i class="material-icons">expand_more</i><b>{{ subjects.name }}</b></div>
            <div class="collapsible-body">
              {% if user.is_tutor %}
                <a href="{% url 'classroom:lesson_create' slug=subjects.slug subject_id=subjects.id %}" class="btn-small"><i class="material-icons">add</i>Add new page</a>
              {% endif %}
                <div class="collection">
                  <br>
                    {% for lesson in subjects.lessons.all %}
                    <a href="{% url 'classroom:lesson_detail' slug=lesson.slug subject=subjects.slug classroom=lesson.Classroom.slug %}" class="collection-item"><i class="material-icons">segment</i> Chapter-{{lesson.position}}: {{lesson.name}}
                        <div class="secondary-content">
                      Completed:
                      <i class="material-icons secondary-content">{% if lesson.id in lesson_completions %}check_circle{% else %}panorama_fish_eye{% endif %}</i>
                     </div>
                    </a>
                  {% endfor %}
                </div>
            </div>
          </li>
        </ul>

      </div>

    </div>


    </div>
</div>
<div class="pb-5"></div>

{% endblock %}

gurufinder/classroom/templates/classroom/studentgrades.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container pb-5">
    <div class="section">
        <h4 class="display-6" style="color:#ff5722;">{{ subject.name }}</h4>
        <div class="divider"></div>
    </div>

    <div class="row g-0">

    <div class="col-md-3">
          <ul class="collection with-header">
            <li class="collection-header"><h4 class="display-6">Classroom</h4></li>
                <a href="{% url 'classroom:course' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Home</a>
                <a href="{% url 'classroom:modules' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Module</a>
                <a href="{% url 'classroom:submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Submissions</a>
                <a href="{% url 'classroom:questions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Questions</a>
              <a href="{% url 'classroom:lesson_list'  slug=subject.slug subject_id=subject.id %}" class="collection-item">Extra Content</a>


              <li class="collection-header"><h4 class="display-6">Teacher</h4></li>
              <a href="{% url 'classroom:student-submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item active">Student Submissions</a>


          </ul>
    </div>

    <div class="col-md-9 gx-5">

      <div class="section">
        <h4 class="display-6">Student submissions</h4>

          <table>
            <thead>
              <tr>
                  <th>Student</th>
                  <th>Assignment</th>
                  <th>Due</th>
                  <th>Submitted</th>
                  <th>Status</th>
                  <th>Score</th>
                  <th>Out of</th>
                  <th>Graded by</th>
                  <th>Grade</th>
              </tr>
            </thead>

            <tbody>
            {% for grade in grades %}
              <tr>
                <td>{{ grade.submission.user.get_full_name|title }}</td>
                <td>{{ grade.submission.assignment.title }}</td>
                <td>{{ grade.submission.assignment.due }}</td>
                <td>{{ grade.submission.date }}</td>
                <td><b>{{ grade.status }}</b></td>
                <td>{{ grade.points }}</td>
                <td>{{ grade.submission.assignment.points }}</td>
                <td>{{ grade.graded_by.get_full_name|title }}</td>
                <td><a href="{% url 'classroom:grade-submission' slug=subject.slug subject_id=subject.id grade_id=grade.id %}"><i class="material-icons">mode</i>Grade</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>



      </div>

    </div>


    </div>
</div>
<div class="pb-5"></div>
<div class="pb-5"></div>


{% endblock %}