gurufinder/classroom/urls.py
from django.urls import path
from . import views

from module.views import course_modules, new_module
from page.views import new_page_module, page_detail, mark_page_as_done
from quiz.views import new_quiz, new_question, quiz_detail, take_quiz, submit_attempt, attempt_detail
from assignment.views import new_assignment, assignment_detail, new_submission
from question.views import new_student_question, questions, question_detail, mark_as_answer, vote_answer




app_name = 'classroom'
urlpatterns = [
    path('', views.ClassroomListView.as_view(), name='classroom_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/<int:subject_id>/', views.course_detail, name='course'),
    path('<slug:slug>/<int:subject_id>/modules/', course_modules, name='modules'),
    path('<slug:slug>/<int:subject_id>/modules/new-module/', new_module, name='new-module'),
    #pages
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/new-page/', new_page_module, name='new-page'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/', page_detail, name='page-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/done/', mark_page_as_done, name='mark-page-as-done'),

    #Quizzes
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/new-quiz', new_quiz, name='new-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/new-question', new_question, name='new-question'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/', quiz_detail, name='quiz-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take', take_quiz, name='take-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take/submit', submit_attempt, name='submit-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/<int:attempt_id>/results', attempt_detail, name='attempt-detail'),

    #Assignment
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/new-assignment', new_assignment, name='new-assignment'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>', assignment_detail, name='assignment-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>/start', new_submission, name='start-assignment'),

    #Submissions
	path('<slug:slug>/<int:subject_id>/submissions', views.submissions, name='submissions'),
	path('<slug:slug>/<int:subject_id>/student-submissions', views.student_submissions, name='student-submissions'),
	path('<slug:slug>/<int:subject_id>/submissions/<int:grade_id>/grade', views.grade_submission, name='grade-submission'),

    #Questions
    path('<slug:slug>/<int:subject_id>/questions', questions, name='questions'),
    path('<slug:slug>/<int:subject_id>/questions/new-question', new_student_question, name='new-student-question'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>', question_detail, name='question-detail'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/vote', vote_answer, name='vote-answer'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/<int:answer_id>/mark-as-answer', mark_as_answer, name='mark-as-answer'),

    #extra content
    path('<slug:slug>/<int:subject_id>/extra-content', views.LessonListView.as_view(), name='lesson_list'),
    path('<slug:slug>/<int:subject_id>/extra-content/create', views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    # path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/<int:lesson_id>/', views.lesson_completed, name='lesson_complete'),
    # path('<str:classroom>/<str:subject>/<slug:slug>/<int:id>/', views.lesson_not_completed, name='lesson_not_completed'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),
    path('<str:classroom>/<int:subject_id>/extra-content/<int:lesson_id>/mark-as-done/', views.mark_lesson_as_done,name='mark-lesson-as-done'),

]

gurufinder/direct/urls.py
from django.urls import path, include
from . import views

app_name = 'direct'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('message/<username>', views.directs, name='message'),
    path('send/', views.send_direct, name='send_direct'),
    path('new/', views.user_search, name='usersearch'),
    path('new/<username>', views.new_conversation, name='newconversation'),
]

gurufinder/gurufinder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls
from accounts import views as accounts_views
from accounts.views import TutorListView, TutorDetailView, BookingView, SearchTutorLanguage #ApplicationView,

urlpatterns = [
    path('', accounts_views.index, name='index'),
    path('about/', accounts_views.about, name='about'),
    path('how-it-works/', accounts_views.how_it_works, name='how_it_works'),
    path('start-tutoring/', accounts_views.tutor_application, name='application'),
    path('search-for-tutors/', TutorListView.as_view(), name='tutor_list'),
    path('search-for-tutors/search-language/', SearchTutorLanguage.as_view(), name='search_language'),
    path('search-for-tutors/<int:pk>/', TutorDetailView.as_view(), name='tutor_detail'),
    path('search-for-tutors/<int:pk>/book/', BookingView.as_view(), name='booking'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('classroom.urls')),
    path('accounts/', include('accounts.urls')),
    path('messages/', include('direct.urls')),
    path('admin/', admin.site.urls),
    path('email/', include(email_urls)),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gurufinder/module/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

from page.models import Page
from quiz.models import Quizzes
from assignment.models import Assignment

# Create your models here.

class Module(models.Model):
	title = models.CharField(max_length=150)
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='module_owner')
	hours = models.PositiveIntegerField()
	pages = models.ManyToManyField(Page)
	quizzes = models.ManyToManyField(Quizzes)
	assignments = models.ManyToManyField(Assignment)

	def __str__(self):
		return self.title

gurufinder/module/forms.py
from django import forms
from module.models import Module

class NewModuleForm(forms.ModelForm):
	title = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)
	hours = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)

	class Meta:
		model = Module
		fields = ('title', 'hours',)

gurufinder/module/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.urls import reverse_lazy
from module.forms import NewModuleForm
from module.models import Module
from classroom.models import Subject

from completion.models import Completion
# Create your views here.

def new_module(request, **kwargs):
	user = request.user
	subject = Subject.objects.get(id=kwargs.get('subject_id'))
	id = kwargs.get('subject_id')

	if user != subject.classroom.bookings.tutor_id.user:
		return HttpResponseForbidden()
	else:
		if request.method == 'POST':
			form = NewModuleForm(request.POST)
			if form.is_valid():
				title = form.cleaned_data.get('title')
				hours = form.cleaned_data.get('hours')
				m = Module.objects.create(title=title, hours=hours, user=user)
				subject.modules.add(m)
				subject.save()
				return redirect('classroom:modules', slug=subject.slug, subject_id=id)

		else:
			form = NewModuleForm()

	context = {
		'form': form,
	}

	return render(request, 'module/newmodule.html', context)



def course_modules(request, **kwargs):
	user = request.user
	subject = Subject.objects.get(id=kwargs.get('subject_id'))

	page_completions = Completion.objects.filter(user=user, subject=subject).values_list('page__pk', flat=True)
	quiz_completions = Completion.objects.filter(user=user, subject=subject).values_list('quiz__pk', flat=True)
	assignment_completions = Completion.objects.filter(user=user, subject=subject).values_list('assignment__pk', flat=True)


	context = {
		'subject': subject,
		'page_completions': page_completions,
		'quiz_completions': quiz_completions,
		'assignment_completions': assignment_completions,
	}

	return render(request, 'module/modules.html', context)

gurufinder/module/templates/module/modules.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container pb-5">
    <div class="section">
        <h4 class="display-6" style="color:#ff5722;">{{ subject.name }}</h4>
        <div class="divider"></div>
    </div>

    <div class="row g-0">

        <div class="col-lg-3">
              <ul class="collection with-header">
                <li class="collection-header"><h4 class="display-6" >Classroom</h4></li>
                <a href="{% url 'classroom:course' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Home</a>
                <a href="{% url 'classroom:modules' slug=subject.slug  subject_id=subject.id %}" class="collection-item active">Module</a>
                <a href="{% url 'classroom:submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Submissions</a>
                <a href="{% url 'classroom:questions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Questions</a>
                  <a href="{% url 'classroom:lesson_list'  slug=subject.slug subject_id=subject.id %}" class="collection-item">Extra Content</a>


                  {% if user.is_tutor %}
                <li class="collection-header"><h4 class="display-6">Teacher</h4></li>
                <a href="{% url 'classroom:student-submissions' slug=subject.slug  subject_id=subject.id %}" class="collection-item">Student Submissions</a>
                    {% endif %}

              </ul>
        </div>

    <div class="col-lg-9 gx-5">

      {% if user.is_tutor %}
        <a href="{% url 'classroom:new-module' slug=subject.slug  subject_id=subject.id %}" class="btn-floating btn-large waves-effect waves-light red right"><i class="material-icons">add</i></a>
      {% endif %}

      <div class="section">
        <h4 class="display-6">Modules</h4>
        <div class="divider"></div>

        <ul class="collapsible">
          {% for module in subject.modules.all %}
          <li>
            <div class="collapsible-header"><i class="material-icons">expand_more</i><b>{{ module.title }}</b></div>
            <div class="collapsible-body">
              {% if user.is_tutor %}
                <a href="{% url 'classroom:new-page' slug=subject.slug subject_id=subject.id module_id=module.id %}" class="btn-small"><i class="material-icons">add</i>Add new page</a>
                <a href="{% url 'classroom:new-quiz' slug=subject.slug subject_id=subject.id module_id=module.id %}" class="btn-small"><i class="material-icons">add</i>Add new quiz</a>
                <a href="{% url 'classroom:new-assignment' slug=subject.slug subject_id=subject.id module_id=module.id %}" class="btn-small"><i class="material-icons">add</i>add new assignment</a>
              {% endif %}
                <div class="collection">
                  <br>
                  {% for page in module.pages.all %}
                    <a href="{% url 'classroom:page-detail' slug=subject.slug subject_id=subject.id module_id=module.id page_id=page.id %}" class="collection-item"><i class="material-icons">segment</i> {{ page.title }}
                     <div class="secondary-content">
                      Completed:
                      <i class="material-icons secondary-content">{% if page.id in page_completions %}check_circle{% else %}panorama_fish_eye{% endif %}</i>
                     </div>
                    </a>
                  {% endfor %}
                  {% for quiz in module.quizzes.all %}
                    <a href="{% url 'classroom:quiz-detail' slug=subject.slug subject_id=subject.id module_id=module.id quiz_id=quiz.id %}" class="collection-item"><i class="material-icons">fact_check</i> {{ quiz.title }}
                     <div class="secondary-content">
                      Completed:
                      <i class="material-icons secondary-content">{% if quiz.id in quiz_completions %}check_circle{% else %}panorama_fish_eye{% endif %}</i>
                     </div>
                    </a>
                  {% endfor %}
                  {% for assignment in module.assignments.all %}
                    <a href="{% url 'classroom:assignment-detail' slug=subject.slug subject_id=subject.id module_id=module.id assignment_id=assignment.id %}" class="collection-item"><i class="material-icons">fact_check</i> {{ assignment.title }}
                     <div class="secondary-content">
                      Completed:
                      <i class="material-icons secondary-content">{% if assignment.id in assignment_completions %}check_circle{% else %}panorama_fish_eye{% endif %}</i>
                     </div>
                    </a>
                  {% endfor %}
                </div>
            </div>
          </li>
          {% endfor %}
        </ul>

      </div>

    </div>


    </div>
</div>
<div class="pb-5"></div>

{% endblock %}

gurufinder/module/templates/module/newmodule.html
{% extends 'base.html' %}
{% load static %}

        
{% block content %}

  <div class="container center-align pb-5 pt-5">
      <div class="col-lg-12">


        <form method="post" enctype="multipart/form-data" action="" role="form">
            {% csrf_token %}
          <h3 class="display-6" style="color:#ff5722;">Let's create a new module!</h3>


                <div class="input-field col-lg-12">
                  {{ form.title }}
                  <label for="title">Title</label>
                </div>

                <div class="input-field col-lg-12">
                  {{ form.hours }}
                  <label for="description">Hours</label>
                </div>


            <div class="row">
              <div class="col-lg-12">
                <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
              </div>
            </div>


            <div class="field">
            <p class="control">
              <button type="submit" value="login" class="btn waves-effect waves-light">
                Create new module
              </button>
            </p>
          </div>

        </form>

      </div>
    </div>
  <div/>

{% endblock %}