gurufinder/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import SignUpView, StudentSignUpView, TutorSignUpView, ProfileView, ProfileUpdateView, TutorBookedSession, ActiveSession
from . import views as acccount_views

app_name = 'accounts'
urlpatterns = [
    path('signup/', include([
        path('', SignUpView.as_view(), name='signup'),
        path('student/', StudentSignUpView.as_view(), name='student_signup'),
        path('tutor/', TutorSignUpView.as_view(), name='tutor_signup'),
    ])),
    path('student-wallet/', acccount_views.student_wallet, name='student_wallet'),
    path('tutor-wallet/', acccount_views.tutor_wallet, name='tutor_wallet'),
    # path('student-wallet/add-amount/', acccount_views.student_add_amount, name='student_add_amount'),
    path('booked-sessions/', ActiveSession.as_view(), name='booked_sessions'),
    path('booked-sessions/end-session/<int:id>/', acccount_views.end_session, name='end_session'),
    path('end-session-rating-student/<int:id>/', acccount_views.end_session_rating_student, name='end_session_rating_student'),
    path('end-session-rating-tutor/<int:id>/', acccount_views.end_session_rating_tutor,name='end_session_rating_tutor'),
    path('booked-requests/', TutorBookedSession.as_view(), name='tutor_bookings'),
    path('booked-requests/deny/<int:id>/', acccount_views.deny_request, name='deny_request'),
    path('booked-requests/accept/<int:id>/', acccount_views.accept_request, name='accept_request'),
    path('availability/', acccount_views.availability, name='availability'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<username>/', ProfileUpdateView.as_view(), name='profile_update'),
]

gurufinder/classroom/urls.py
from django.urls import path
from . import views

from module.views import course_modules, new_module
from page.views import new_page_module, page_detail, mark_page_as_done
from quiz.views import new_quiz, new_question, quiz_detail, take_quiz, submit_attempt, attempt_detail
from assignment.views import new_assignment, assignment_detail, new_submission
from question.views import new_student_question, questions, question_detail, mark_as_answer, vote_answer




app_name = 'classroom'
urlpatterns = [
    path('', views.ClassroomListView.as_view(), name='classroom_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/<int:subject_id>/', views.course_detail, name='course'),
    path('<slug:slug>/<int:subject_id>/modules/', course_modules, name='modules'),
    path('<slug:slug>/<int:subject_id>/modules/new-module/', new_module, name='new-module'),
    #pages
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/new-page/', new_page_module, name='new-page'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/', page_detail, name='page-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/pages/<int:page_id>/done/', mark_page_as_done, name='mark-page-as-done'),

    #Quizzes
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/new-quiz', new_quiz, name='new-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/new-question', new_question, name='new-question'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/', quiz_detail, name='quiz-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take', take_quiz, name='take-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/take/submit', submit_attempt, name='submit-quiz'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/quiz/<int:quiz_id>/<int:attempt_id>/results', attempt_detail, name='attempt-detail'),

    #Assignment
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/new-assignment', new_assignment, name='new-assignment'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>', assignment_detail, name='assignment-detail'),
    path('<slug:slug>/<int:subject_id>/modules/<int:module_id>/assignment/<int:assignment_id>/start', new_submission, name='start-assignment'),

    #Submissions
	path('<slug:slug>/<int:subject_id>/submissions', views.submissions, name='submissions'),
	path('<slug:slug>/<int:subject_id>/student-submissions', views.student_submissions, name='student-submissions'),
	path('<slug:slug>/<int:subject_id>/submissions/<int:grade_id>/grade', views.grade_submission, name='grade-submission'),

    #Questions
    path('<slug:slug>/<int:subject_id>/questions', questions, name='questions'),
    path('<slug:slug>/<int:subject_id>/questions/new-question', new_student_question, name='new-student-question'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>', question_detail, name='question-detail'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/vote', vote_answer, name='vote-answer'),
    path('<slug:slug>/<int:subject_id>/questions/<int:question_id>/<int:answer_id>/mark-as-answer', mark_as_answer, name='mark-as-answer'),

    #extra content
    path('<slug:slug>/<int:subject_id>/extra-content', views.LessonListView.as_view(), name='lesson_list'),
    path('<slug:slug>/<int:subject_id>/extra-content/create', views.LessonCreateView.as_view(), name='lesson_create'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    # path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/<int:lesson_id>/', views.lesson_completed, name='lesson_complete'),
    # path('<str:classroom>/<str:subject>/<slug:slug>/<int:id>/', views.lesson_not_completed, name='lesson_not_completed'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('<str:classroom>/<str:subject>/extra-content/<slug:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),
    path('<str:classroom>/<int:subject_id>/extra-content/<int:lesson_id>/mark-as-done/', views.mark_lesson_as_done,name='mark-lesson-as-done'),

]

gurufinder/direct/urls.py
from django.urls import path, include
from . import views

app_name = 'direct'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('message/<username>', views.directs, name='message'),
    path('send/', views.send_direct, name='send_direct'),
    path('new/', views.user_search, name='usersearch'),
    path('new/<username>', views.new_conversation, name='newconversation'),
]

gurufinder/gurufinder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls
from accounts import views as accounts_views
from accounts.views import TutorListView, TutorDetailView, BookingView, SearchTutorLanguage #ApplicationView,

urlpatterns = [
    path('', accounts_views.index, name='index'),
    path('about/', accounts_views.about, name='about'),
    path('how-it-works/', accounts_views.how_it_works, name='how_it_works'),
    path('start-tutoring/', accounts_views.tutor_application, name='application'),
    path('search-for-tutors/', TutorListView.as_view(), name='tutor_list'),
    path('search-for-tutors/search-language/', SearchTutorLanguage.as_view(), name='search_language'),
    path('search-for-tutors/<int:pk>/', TutorDetailView.as_view(), name='tutor_detail'),
    path('search-for-tutors/<int:pk>/book/', BookingView.as_view(), name='booking'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('classroom.urls')),
    path('accounts/', include('accounts.urls')),
    path('messages/', include('direct.urls')),
    path('admin/', admin.site.urls),
    path('email/', include(email_urls)),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gurufinder/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- star ratings css -->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet"
    <!-- tutor list css -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />



    <!-- to connect a css -->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/featurette.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tutor_list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tutor_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/chatbox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/search_bar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/our_team.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/aboutus.css' %}">


      <!-- CSS  -->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
      <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

    <title>{%block title%}{%endblock%}</title>


</head>
<body>
    <header class="py-3 bg-dark text-white shadow">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <a class="navbar-brand"  href="{% url 'index' %}"><h5 style="line-height:80%;"><span class="multicolortext">𝓖𝓾𝓻𝓾𝓯𝓲𝓷𝓭𝓮𝓻</span></h5></a>
              <li><a href="{% url 'index' %}" class="nav-link mt-3 px-2 text-white">Home</a></li>
<!--                <li><a href="{% url 'how_it_works' %}" class="nav-link mt-3 px-2 text-white">How it Works</a></li>-->
                {% if user.is_student %}
                    <li><a href="{% url 'tutor_list' %}" class="nav-link mt-3  px-2 text-white">Search For Tutors</a></li>
                    <!--<li><a href="#" class="nav-link px-2 text-white">Request A Tutor</a></li>-->
                {% elif user.is_tutor and user.tutor_profile.is_validated == False %}
                    <li><a href="{% url 'application' %}" class="nav-link mt-3 px-2 text-white">Start Tutoring</a></li>
                <!--comment out -->
                {# {% elif user.is_tutor and user.tutor_profile.is_validated or user.is_superuser %} #}
                    <!--<li><a href="#" class="nav-link px-2 text-white">Book A Lesson</a></li>-->
                {% endif %}
              <li><a href="{% url 'about' %}" class="nav-link mt-3 px-2 text-white">About Us</a></li>
            </ul>

            <div class="text-end">
                {% if user.is_authenticated and user.is_student or user.is_superuser%}
                    <div class="dropdown text-end">
                      <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.image.url }}" alt="{{ user.username }}" width="32" height="32" class="rounded-circle">

                      </a>
                      <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a></li>
                          <li><a class="dropdown-item" href="{% url 'accounts:booked_sessions' %}">My Sessions</a></li>
                          <!--<li><a class="dropdown-item" href="{% url 'classroom:classroom_list' %}">Courses</a></li>-->
                          <li><a class="dropdown-item" href="{% url 'accounts:student_wallet' %}">My Wallet</a></li>
                          {% if directs_count %}
                          <li><a class="dropdown-item" href="{% url 'direct:inbox' %}">Messages <span class="badge bg-secondary">New</span></a></li>
                          {% else %}
                          <li><a class="dropdown-item" href="{% url 'direct:inbox' %}">Messages</a></li>
                          {% endif %}
                        <!-- <li><a class="dropdown-item" href="#">View/Edit Profile</a></li> -->
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                      </ul>
                    </div>
                {% elif user.is_authenticated and user.is_tutor %}
                    <div class="dropdown text-end">
                      <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.image.url }}" alt="{{ user.username }}" width="32" height="32" class="rounded-circle">

                      </a>
                      <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a></li>
                          {% if user.tutor_profile.is_validated %}
                          <li><a class="dropdown-item" href="{% url 'accounts:booked_sessions' %}">My Sessions</a></li>
                          <li><a class="dropdown-item" href="{% url 'accounts:tutor_wallet' %}">My Wallet</a></li>
                          <li><a class="dropdown-item" href="{% url 'accounts:tutor_bookings' %}">Book Requests</a></li>
                          <!--<li><a class="dropdown-item" href="{% url 'classroom:classroom_list' %}">Courses</a></li>-->
                          {% elif user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'classroom:classroom_list' %}">Courses</a></li>
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                          {% endif %}
                        <li><a class="dropdown-item" href="{% url 'direct:inbox' %}">Messages</a></li>
                          {% if user.tutor_profile.is_validated %}
                        <li><a class="dropdown-item" href="{% url 'accounts:availability' %}">Availability</a></li>
                          {% endif %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                      </ul>
                    </div>
                {% else %}
                    <a href="{% url 'accounts:login' %}"class="btn btn-outline-light me-2" role="button">Login</a>
                    <a href="{% url 'accounts:signup' %}"class="btn btn-warning" role="button">Sign-up</a>
                {% endif %}
            </div>
          </div>
        </div>
  </header>
    {% if messages %}
        {% for message in messages %}
            <div class="container">
                <div class="row">
                    <div class="text-center my-3">
                    <!--<div class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 mt-2">-->
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}

    <!-- FOOTER -->
    <footer class="w-100 py-4 flex-shrink-0">
        <div class="container py-4">
            <div class="row gy-4 gx-5">
                <div class="col-lg-4 col-md-6">
                    <h5 class="h1 text-white">GuruFinder</h5>
                    <p class="small text-muted">Find the right tutor for you</p>
                    <p class="small text-muted mb-0">&copy; Copyrights. All rights reserved. <a class="text-primary" href="#">gurufinder.com</a></p>
                </div>
                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Quick links</h5>
                    <ul class="list-unstyled text-muted">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Quick links</h5>
                    <ul class="list-unstyled text-muted">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6">
                    <h5 class="text-white mb-3">Let's talk</h5>
                    <p class="small text-muted">EMAIL: princess.fev-14@cpu.edu.ph</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!--  Scripts-->
      <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="{% static 'js/materialize.js' %}"></script>
      <script src="{% static 'js/init.js' %}"></script>
      <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
      <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

    <!-- star ratings script -->
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <!-- htmx -->
    <script src="https://unpkg.com/htmx.org@1.1.0"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>



</body>
</html>

gurufinder/templates/confirm_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
  {% if success %}
    {{ user.username }}, your account is confirmed!
  {% else %}
    Error, invalid token!
  {% endif %}
</body>
</html>

gurufinder/templates/mail_body.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
      h1{ color: blue; }
    </style>
</head>
<body>
  <h1>You are almost there, {{ user.username }}!</h1><br>
  <h2>Please click <a href="{{ link }}">here</a> to confirm your account</h2>
  <h2>The token expires on {{ expiry|time:"TIME_FORMAT" }}</h2>
</body>
</html>